name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.6

      - name: Install tools
        run: python -m pip3 install --upgrade pip3 pytest requests pandas sqlalchemy mysqlclient

      - name: Test with unittest
        run: |
          python3 -m unittest test.py
